version: "3.8"
services:
  product-service:
    build: .
    ports:
      - "4001:4001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=disara7
      - DB_NAME=mfe_products_db
      - PORT=4001
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: disara7
      MYSQL_DATABASE: mfe_products_db
    ports:
      - "3306:3306"
